services:
  db:
    image: postgres:16-alpine
    container_name: skysync_db
    environment:
      POSTGRES_DB: TechHubDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - skysync_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TechHubDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./SkySync_Solutions
      dockerfile: ./SkySync.API/Dockerfile
    container_name: skysync_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Database=TechHubDB;Username=postgres;Password=12345
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  skysync_db_data:
