// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkySync.Infrastructure;

#nullable disable

namespace SkySync.Infrastructure.Migrations
{
    [DbContext(typeof(SkySyncDbContext))]
    partial class SkySyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkySync.Domain.Entidades.Aeropuerto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Ciudad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Aeropuertos");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Avion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("Capacidad");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Modelo");

                    b.HasKey("Id");

                    b.ToTable("Aviones");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("CuposDisponibles");

                    b.Property<int>("CuposMaximos")
                        .HasColumnType("integer")
                        .HasColumnName("CuposMaximos");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.HorasVuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destino")
                        .HasColumnType("text")
                        .HasColumnName("Destino");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<decimal>("Horas")
                        .HasColumnType("numeric")
                        .HasColumnName("Horas");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<string>("Origen")
                        .HasColumnType("text")
                        .HasColumnName("Origen");

                    b.Property<string>("TipoVuelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TipoVuelo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("HorasVuelos");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Licencia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Practica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean")
                        .HasColumnName("Completada");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<decimal>("Horas")
                        .HasColumnType("numeric")
                        .HasColumnName("Horas");

                    b.Property<string>("Instructor")
                        .HasColumnType("text")
                        .HasColumnName("Instructor");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("Practicas");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("integer")
                        .HasColumnName("ClaseId");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaReserva");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioId");

                    b.Property<int>("VueloId")
                        .HasColumnType("integer")
                        .HasColumnName("VueloId");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("Direccion");

                    b.Property<string>("Licencia")
                        .HasColumnType("text")
                        .HasColumnName("Licencia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Rol");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SkySync.Domain.Entidades.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("CuposDisponibles");

                    b.Property<int>("CuposMaximos")
                        .HasColumnType("integer")
                        .HasColumnName("CuposMaximos");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Destino");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaSalida");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Origen");

                    b.HasKey("Id");

                    b.ToTable("Vuelos");
                });
#pragma warning restore 612, 618
        }
    }
}
