-- 1. Aeropuertos (Catálogo esencial para origen y destino)
CREATE TABLE Aeropuertos (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodigoIATA" text NOT NULL, -- Ej: BOG, MDE, JKF
    "Nombre" text NOT NULL,
    "Ciudad" text NOT NULL,
    "Pais" text NOT NULL,
    CONSTRAINT "PK_Aeropuertos" PRIMARY KEY ("Id")
);

-- 2. Aviones (Datos reales de la flota)
CREATE TABLE Aviones (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Matricula" text NOT NULL, -- Ej: HK-4508
    "Modelo" text NOT NULL,    -- Ej: Boeing 737 MAX
    "Capacidad" integer NOT NULL,
    CONSTRAINT "PK_Aviones" PRIMARY KEY ("Id")
);

-- 3. Pilotos (Mejorado con credenciales)
CREATE TABLE Pilotos (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "NumeroLicencia" text NOT NULL,
    "Cargo" text NOT NULL, -- Ej: Capitán, Primer Oficial
    "Contrasena" text NOT NULL,
    "HorasVuelo" integer DEFAULT 0,
    CONSTRAINT "PK_Pilotos" PRIMARY KEY ("Id")
);

-- 4. Clases de Vuelo (Turista, Ejecutiva, etc.)
CREATE TABLE Clases (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NULL,
    CONSTRAINT "PK_Clases" PRIMARY KEY ("Id")
);

-- 5. Usuarios / Pasajeros (Teléfono corregido a text y agregado documento)
CREATE TABLE Usuarios (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "DocumentoIdentidad" text NOT NULL, -- Cédula o Pasaporte
    "Correo" text NOT NULL,
    "Contrasena" text NOT NULL,
    "Telefono" text NULL, 
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

-- 6. Vuelos (La entidad central que une la operación)
CREATE TABLE Vuelos (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroVuelo" text NOT NULL, -- Ej: AV930
    "OrigenId" integer NOT NULL,
    "DestinoId" integer NOT NULL,
    "AvionId" integer NOT NULL,
    "PilotoId" integer NOT NULL,
    "FechaSalida" timestamp with time zone NOT NULL,
    "FechaLlegada" timestamp with time zone NOT NULL,
    "Estado" text NOT NULL, -- Ej: Programado, En Vuelo, Aterrizado
    CONSTRAINT "PK_Vuelos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vuelos_Origen" FOREIGN KEY ("OrigenId") REFERENCES "Aeropuertos"("Id"),
    CONSTRAINT "FK_Vuelos_Destino" FOREIGN KEY ("DestinoId") REFERENCES "Aeropuertos"("Id"),
    CONSTRAINT "FK_Vuelos_Aviones" FOREIGN KEY ("AvionId") REFERENCES "Aviones"("Id"),
    CONSTRAINT "FK_Vuelos_Pilotos" FOREIGN KEY ("PilotoId") REFERENCES "Pilotos"("Id")
);

-- 7. Reservas (Conecta al usuario con su vuelo, asiento y clase)
CREATE TABLE Reservas (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "VueloId" integer NOT NULL,
    "ClaseId" integer NOT NULL,
    "Asiento" text NOT NULL, -- Ej: 12A
    "FechaReserva" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Reservas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservas_Usuarios" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios"("Id"),
    CONSTRAINT "FK_Reservas_Vuelos" FOREIGN KEY ("VueloId") REFERENCES "Vuelos"("Id"),
    CONSTRAINT "FK_Reservas_Clases" FOREIGN KEY ("ClaseId") REFERENCES "Clases"("Id")
);