-- Crear la tabla de Productos
CREATE TABLE "Productos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "nombre" text NOT NULL,
    "descripcion" text,
    "precio" numeric(10, 2) NOT NULL,
    "stock" integer NOT NULL,
    "categoria" text,
    CONSTRAINT "PK_Productos" PRIMARY KEY ("Id")
);

-- Crear la tabla de Clases
CREATE TABLE "Clases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NULL,
    CONSTRAINT "PK_Clases" PRIMARY KEY ("Id")
);

-- Crear la tabla de Usuarios
CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Correo" text NOT NULL,
    "Contrasena" text NOT NULL,
    "Direccion" text,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);