using TechHub.Application.Interfaces;
using TechHub.Application.Servicios;
using TechHub.Infrastructure;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddDbContext<TechHubDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")
        ?? builder.Configuration["Database:ConnectionString"]
        ?? "Host=localhost;Database=TechHubDB;Username=postgres;Password=12345"));

builder.Services.AddControllers();



builder.Services.AddCors(options =>
{
    options.AddPolicy("PermitirAngular", policy =>
    {
        policy.WithOrigins("http://localhost:4200")
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});
builder.Services.AddOpenApi();

builder.Services.AddScoped<IAgendaService, AgendaService>();
builder.Services.AddScoped<IUsuariosService, UsuariosService>();
builder.Services.AddScoped<IAeropuertosService, AeropuertosService>();
builder.Services.AddScoped<IAvionesService, AvionesService>();
builder.Services.AddScoped<IPilotosService, PilotosService>();
builder.Services.AddScoped<IVuelosService, VuelosService>();
builder.Services.AddScoped<IPracticasService, PracticasService>();
builder.Services.AddScoped<IHorasVueloService, HorasVueloService>();


var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<TechHubDbContext>();
    try
    {
        db.Database.EnsureCreated();

        var conn = db.Database.GetDbConnection();
        await conn.OpenAsync();
        using var cmd = conn.CreateCommand();

        cmd.CommandText = @"
            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Usuarios' AND column_name='Rol') THEN
                    ALTER TABLE ""Usuarios"" ADD COLUMN ""Rol"" text NOT NULL DEFAULT 'Pasajero';
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Usuarios' AND column_name='Licencia') THEN
                    ALTER TABLE ""Usuarios"" ADD COLUMN ""Licencia"" text NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='Practicas') THEN
                    CREATE TABLE ""Practicas"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""UsuarioId"" integer NOT NULL,
                        ""Fecha"" timestamp with time zone NOT NULL,
                        ""Tipo"" text NOT NULL DEFAULT 'Teorica',
                        ""Horas"" numeric NOT NULL DEFAULT 0,
                        ""Descripcion"" text NULL,
                        ""Instructor"" text NULL,
                        ""Completada"" boolean NOT NULL DEFAULT false
                    );
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='HorasVuelos') THEN
                    CREATE TABLE ""HorasVuelos"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""UsuarioId"" integer NOT NULL,
                        ""Fecha"" timestamp with time zone NOT NULL,
                        ""Horas"" numeric NOT NULL DEFAULT 0,
                        ""TipoVuelo"" text NOT NULL DEFAULT 'Local',
                        ""Origen"" text NULL,
                        ""Destino"" text NULL,
                        ""Notas"" text NULL
                    );
                END IF;
            END $$;
        ";
        cmd.ExecuteNonQuery();
        Console.WriteLine("Migraciones aplicadas/verificadas correctamente.");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error al aplicar migraciones: {ex.Message}");
    }
}

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();


    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/openapi/v1.json", "TechHub API");
    });
}

app.UseCors("PermitirAngular");

app.UseAuthorization();

app.MapControllers();

app.MapGet("/", () => Results.Redirect("/swagger"));

app.Run();